### ISSUE TITLE
Long names

### ISSUE THREAD

**Issue by tischi** [mobie-org/mobie-viewer-fiji#61]
@constantinpape @vzinche 

Some image names are very long and cause the buttons in the UI to look ugly, see below:

<img width="548" alt="image" src="https://user-images.githubusercontent.com/2157566/74405726-1d953000-4e2e-11ea-88df-cf226226a073.png">

We could 

1. make the whole UI by default wider to accommodate this?
1. maybe not show the whole name?
1. other ideas?

**Comment by vzinche** [comment]
I would actually drop the whole 'sbem-6dpf-whole' and 'prospr-6dpf-whole' part

**Comment by constantinpape** [comment]
I don't think we should drop parts of the name in there.
If we want to extend the browser to more data all of this will be relevant.
E.g. if we get a second SBEM specimen it would be called `sbem-6dpf-2-whole`, so if we drop this we can't distinguish between those any more.
