### ISSUE TITLE
Enable changing the version without restart

### ISSUE THREAD

**Issue by constantinpape** [mobie-org/mobie-viewer-fiji#84]
I am using the versions to store related but separate datasets in https://git.embl.de/pape/covid-em.
It would be great if one could switch between those without restarting the plugin.

**Comment by tischi** [comment]
> I am using the versions to store related but separate datasets...

Maybe using versions for this is not the right thing to do, is it?
Maybe we can find another way? Let's talk on the phone...

**Comment by constantinpape** [comment]
We discussed to rename what we call `version` now to `dataset`.
So there will be a `datasets.json`. And then we allow to change between datasets from the gui.

(For now, we only allow for one active dataset; later on when the GUI is unified into a single window, we can enable showing multiple at once.)

**Comment by constantinpape** [comment]
As we have just discussed, we will change the `datasets.json` layout a bit:
```
{
  "dataset": ["ds1", "ds2", ...]
  "default": "ds2"
}
```
So that we know which dataset to open by default to get rid of the initial dataset choosing menu.
The `"default"` field should be optional, if it's not there we just choose one of the datasets.

**Comment by tischi** [comment]
let me know once you have this somewhere then I can test loading it.

**Comment by constantinpape** [comment]
> As long as the autophagosomes one is on gitlab I would suggest the covid-em is our playground.

It's the other way! Autophagosoms are on github and they are our playground.
I have updated this repo now: added a second dataset and updated the `datasets.json`:
https://github.com/constantinpape/autophagosomes-clem
