### ISSUE TITLE
Don't hard-code platy naming pattern

### ISSUE THREAD

**Issue by constantinpape** [mobie-org/mobie-viewer-fiji#85]

**Comment by tischi** [comment]
@constantinpape 
Could you provide an example what you mean by this?

**Comment by constantinpape** [comment]
Right now, the MMB will only open if there is a file called
`sbem-6dpf-1-whole-raw`, see https://github.com/platybrowser/mmb-fiji/blob/0ea134c9780065a915b6f0ac7beda2a73f4faa47/src/main/java/de/embl/cba/platynereis/Constants.java#L7.

This effectively restricts it to the platy naming scheme.

**Comment by tischi** [comment]
I see, but this is only the default file that it should open. 
How should we do it?
Should we maybe add to the repo a `bookmarks/default.json`? I think this would be quite nice, because this can specify a complete view rather than a single file.
And if this file is missing, maybe it should just how **_nothing_** to start with?

**Comment by constantinpape** [comment]
> I see, but this is only the default file that it should open.

Yes, I know. But this still forces one to use the platy naming pattern, because otherwise there are two separate naming patterns and that's even more confusing. 

> How should we do it?
> Should we maybe add to the repo a `bookmarks/default.json`? I think this would be quite nice, because this can specify a complete view rather than a single file.
> And if this file is missing, maybe it should just how **_nothing_** to start with?

Yes, I think that's a good idea.

**Comment by tischi** [comment]
ok, and regarding the naming scheme. I looked through my code and found only this, which extracts the modality:  

- https://github.com/platybrowser/mmb-fiji/blob/master/src/main/java/de/embl/cba/platynereis/platybrowser/PlatyBrowserActionPanel.java#L325

... and this, which essentially throws away all the other information :-)

- https://github.com/platybrowser/mmb-fiji/blob/23740aa4f3f98dc5e59f99d743a6356945dc8ddf/src/main/java/de/embl/cba/platynereis/utils/Utils.java#L396

I think it is good that we have more projects now to see what we really need... 
Maybe we should talk on the phone about this?

**Comment by constantinpape** [comment]
> Maybe we should talk on the phone about this?

Sounds good, let's discuss after the platy meeting or some point later this afternoon.

**Comment by constantinpape** [comment]
Ok, as just discussed, the current solution is fine for now. 
In the long term, we want to define the naming pattern and how it maps to the GUI in the git repo,
but for now we just take the name in front of the first dash as modality.

**Comment by tischi** [comment]
That means also for the new ongoing projects this is not yet critical, right?

**Comment by constantinpape** [comment]
> That means also for the new ongoing projects this is not yet critical, right?

Yes, I think the only critical thing was that the initial layer was hard-coded to  `sbem-6dpf-...-raw`.
And this should be fixed now with the default bookmark, I think.
