### ISSUE TITLE
Support default bookmark

### ISSUE THREAD

**Issue by tischi** [mobie-org/mobie-viewer-fiji#86]
@constantinpape

**Comment by constantinpape** [comment]
As we have just discussed:
We will have a new layout for the bookmarks:
```
misc/bookmarks/
                           default.json
                           bookmarks.json
                           more_bookmarks.json
                           ...
```
The MMB will look for the `default.json` and load the view specified in it.
(If it's not there, no data will be loaded initially).

All the other bookmarks will go to the usual bookmarks tab; but we can keep them in different jsons now in order to add support for #83 later.

**Comment by constantinpape** [comment]
I will add it like this in the next project we are setting up.

**Comment by tischi** [comment]
@constantinpape I wanted to work on this but the autophagosomes repo does not contain such files yet. Did you want to add them? Otherwise we can use the covid-em project as our playground. There I could add the new bookmark structure.

**Comment by constantinpape** [comment]
https://github.com/constantinpape/autophagosomes-clem/blob/master/data/10spd/misc/bookmarks/default.json

**Comment by tischi** [comment]
ok, works now. I also added a Layer to the `default.json`. Because if there is not at least one Layer it crashes, because it cannot show anything...

**Comment by tischi** [comment]
- [ ] I still have to implement it for local image data, so far only did it for remote

**Comment by constantinpape** [comment]
> ok, works now. I also added a Layer to the `default.json`. Because if there is not at least one Layer it crashes, because it cannot show anything...

Makes sense; I updated the script in the autophagosomes repo s.t. it adds the layers field to the bookmark dict now.
